### ISSUE TITLE
github permission errors

### ISSUE THREAD

**Issue by kkdao** [jreesun/krux#17]
hello and great looking project!

when i try to run the first command on a linux OS i get many git@github permission denied errors when it tries to clone each submodule.

when i searched what to do it suggests creating an SSH key for my github account, but i don't understand what that has to do with your repo - apologies for my ignorance!

**Comment by jreesun** [comment]
It looks like you resolved this already, but the problem you were running into was that the krux repo was being cloned with https (probably the default method in your git config), but in the `.gitmodules` file the repos' urls are hard-coded as ssh paths (`git@github.com:user/repo`). If you don't have an ssh key setup already in your git config, it'll fail with the message you mentioned.

I'm reopening this issue though since there may be a better way to define the submodules so that they work automatically for https-only or ssh-only git configs:
https://stackoverflow.com/a/44630028

It looks like the URLs can be defined as relative paths, so I'll try that out in the next few days as a better long-term solution.
